[project]
name = "dctap2shacl"
version = "0.1.0"
description = "BIBFRAME Interoperability Group code for transforming DCTap tsv files into SHACL"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
